#!/usr/bin/python
# -*- coding: utf-8 -*-


String = {
    'wrong_argument': '无效的命令',
    'thanks_to_donate': '帮 Cycoe 买一杯咖啡吧',
    'failed_fetch_login': '抓取登录页面数据失败',
    'max_attempts': '达到最大重试次数',
    'server_unreachable': '可能是远程服务器不可用',
    'username': '学号: ',
    'password': '密码: ',
    'failed_fetch_vertify_code': '抓取验证码失败',
    'retrying': '正在重试...',
    'no_such_a_user': '用户名不存在',
    'wrong_password': '密码错误',
    'wrong_vertify_code': '验证码错误',
    'clean_password': '正在清理错误的密码文件...',
    'empty_vertify_code': '请输入验证码',
    'login_successfully': '登录成功',
    'failed_fetch_report': '抓取报告列表失败',
    're-login': '可能需要重新登录',
    'failed_post_report': '提交抢报告请求失败',
    'login_first': '请先登录',
    'sending_a_test_mail': '正在向你的邮箱发送测试邮件...',
    'check_in_trash_box': '如果没有收到测试邮件，请检查一下垃圾箱中的邮件',
    'sender_mail_address': '发送者邮箱地址: ',
    'nickname': '发送者昵称: ',
    'just_test_connection': '邮箱连接测试',
    'test_connection': '测试 class_robber 与邮箱之间的连接，无需回复。',
    'robbing_report': '检测到报告，开抢...',
    'dozing': '没有报告可抢，开始休眠...',
    'robbed_new_reports': '抢到新报告',
    'site_cleaning': '正在清理现场...',
    'close_session': '正在关闭会话...',
    'exiting': '正在退出...',
    'have_send_a_mail': '已向你的邮箱中发送通知邮件',
    'to_mail': '目标邮箱: ',
    'failed_send_email': '邮件发送失败',
    'check_your_email_address': '请检查你的邮箱或密码设置是否正确',
    'cannot_handle_decode': '无法对邮件的编码进行解析',
    'check_your_computer_name': '请将你的电脑主机名设为英文',
    'alipay': '支付宝',
    'wechat': '微信',
    'not_now': '先用用看',
    'remember_to_donate': '觉得好用别忘了赏我一杯咖啡钱哦',
    'thanks_to_support': '感谢支持！',
    'receiver': '接收邮箱',
    'sender': '发送邮箱',
    'sender_password': '发送邮箱密码',
    'sender_host': '发送邮箱 smtp 主机地址',
    'sender_port': '端口',
    'host_error': 'smtp 主机地址错误',
    'check_your_host': '请检查 stmp 主机地址',
    'check_spell': '输入格式错误',
    'address_doesnt_exist': '邮件地址或主机不存在',
    'change_mail': '默认的发送邮箱 (class_robber@cycoe.cc) 有一定的概率导致邮件发送失败，请设置自己的邮箱进行发送',
    'current': '当前',
}
